name: Postprocess

on: [push, workflow_dispatch]

concurrency:
  group: "all"
  cancel-in-progress: false

jobs:
  postprocess:
    name: Postprocess
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  # To be able to `commit --amend`

      - name: Get changed files
        if: github.event_name == 'push'
        id: changed-files
        uses: tj-actions/changed-files@v40
        with:
          write_output_files: true
          json: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: pip
          cache-dependency-path: .github/requirements.txt

      - name: Install Python dependencies
        working-directory: .github
        run: pip install -r requirements.txt

      - name: Run postprocess
        working-directory: .github/src
        run: python postprocess.py

      - name: Delete temporary files
        run: rm -rf .github/outputs

      - name: Get last commit message
        id: last-commit-message
        run: echo "msg=$(git log -1 --pretty=%s)" >> $GITHUB_OUTPUT

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: ${{ steps.last-commit-message.outputs.msg }}
          commit_options: --amend --no-edit
          push_options: --force
          skip_fetch: true
          commit_user_name: GitHub Actions
          # commit_author: GitHub Actions <41898282+github-actions[bot]@users.noreply.github.com>
