name: README generator

on: push

jobs:
  exec-time:
    name: README generator
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          architecture: x64

      - name: Generate READMEs
        working-directory: ./.github
        run: python readme_generator.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions'
          git commit -am '[AUTO-COMMIT] Updated READMEs'
          git push

      - name: Send Telegram notification
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: Github Action "${{ github.workflow }}" in "${{ github.repository }}" completed
