name: Workflow

on: push

jobs:
  exec-time:
    name: Script execution time counter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7.5
          architecture: x64

      - name: Run readme_generator.py
        working-directory: ./.github
        run: python readme_generator.py

      - name: Commit and push changes
        uses: devops-infra/action-commit-push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_prefix: ""
          commit_message: "[AUTO-COMMIT] Updated READMEs"

      - name: Send Telegram notification
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Github Actions "${{ github.workflow }}" in "${{ github.repository }}" completed.
