name: README generator

on:
  # push:
  workflow_dispatch:

permissions: write-all

jobs:
  exec-time:
    name: README generator
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.SSH_KEY }}

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          architecture: x64

      - name: Generate READMEs
        working-directory: .github
        run: python generate_readme.py

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "[AUTO-COMMIT] Updated READMEs"
          commit_user_name: GitHub Actions
          commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com
          commit_author: GitHub Actions <41898282+github-actions[bot]@users.noreply.github.com>

      # - name: Send Telegram notification
      #   uses: appleboy/telegram-action@master
      #   with:
      #     to: ${{ secrets.TELEGRAM_TO }}
      #     token: ${{ secrets.TELEGRAM_TOKEN }}
      #     message: Github Action "${{ github.workflow }}" in "${{ github.repository }}" completed
